# IRIS FLOWER CLASSIFICATION USING MACHINE LEARNING

In [8]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [9]:
# Load the Iris dataset
iris = load_iris()

# Convert to a pandas DataFrame for easier handling
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target  # Add the species (target) column

# View the first few rows of the dataset
print(df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  


In [10]:
# Split the data into features (X) and target (y)
X = df.iloc[:, :-1].values  # Features (sepal and petal measurements)
y = df['species'].values    # Target (species)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")


Training data shape: (120, 4)
Testing data shape: (30, 4)


In [11]:
# Standardize (scale) the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Model training is done. Now, let's check its performance on the test set.


LogisticRegression()

In [12]:
# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Classification Report (Precision, Recall, F1-score)
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


Accuracy: 100.00%
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [14]:
# Example: Predict the species of a flower with these measurements:
example_flowers = np.array([[5.1, 3.5, 1.4, 0.2],   # Likely Setosa
                            [6.5, 3.0, 5.8, 2.2]])  # Likely Virginica

# Scale the example flowers (use the same scaler as before)
example_flowers_scaled = scaler.transform(example_flowers)

# Predict the species
predictions = model.predict(example_flowers_scaled)

# Map the prediction results to species names
predicted_species = [iris.target_names[p] for p in predictions]
print(f"Predicted species: {predicted_species}")


Predicted species: ['setosa', 'virginica']
